/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.principal;

import javax.swing.ImageIcon;

/**
 *
 * @author jose-
 */
public class Acuerdos extends javax.swing.JFrame {

    /**
     * Creates new form VariedadCerezas
     */
    public Acuerdos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoApp.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContratos = new javax.swing.JButton();
        btnMetodosPago = new javax.swing.JButton();
        btnRenovacion = new javax.swing.JButton();
        btnConvenio = new javax.swing.JButton();
        btnConvenioT = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jHojita = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jAtras = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jImagen = new javax.swing.JLabel();
        jFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContratos.setBackground(new java.awt.Color(51, 51, 51));
        btnContratos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnContratos.setForeground(new java.awt.Color(255, 255, 255));
        btnContratos.setText("Contrato");
        btnContratos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnContratos.setContentAreaFilled(false);
        btnContratos.setFocusPainted(false);
        btnContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContratosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContratosMouseExited(evt);
            }
        });
        getContentPane().add(btnContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, 40));

        btnMetodosPago.setBackground(new java.awt.Color(51, 51, 51));
        btnMetodosPago.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMetodosPago.setForeground(new java.awt.Color(255, 255, 255));
        btnMetodosPago.setText("Metodo de Pago");
        btnMetodosPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnMetodosPago.setContentAreaFilled(false);
        btnMetodosPago.setFocusPainted(false);
        btnMetodosPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMetodosPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMetodosPagoMouseExited(evt);
            }
        });
        getContentPane().add(btnMetodosPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 40));

        btnRenovacion.setBackground(new java.awt.Color(51, 51, 51));
        btnRenovacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRenovacion.setForeground(new java.awt.Color(255, 255, 255));
        btnRenovacion.setText("Renovación");
        btnRenovacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRenovacion.setContentAreaFilled(false);
        btnRenovacion.setFocusPainted(false);
        btnRenovacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRenovacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRenovacionMouseExited(evt);
            }
        });
        getContentPane().add(btnRenovacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 40));

        btnConvenio.setBackground(new java.awt.Color(51, 51, 51));
        btnConvenio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConvenio.setForeground(new java.awt.Color(255, 255, 255));
        btnConvenio.setText("Convenio");
        btnConvenio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnConvenio.setContentAreaFilled(false);
        btnConvenio.setFocusPainted(false);
        btnConvenio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConvenioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConvenioMouseExited(evt);
            }
        });
        getContentPane().add(btnConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, 40));

        btnConvenioT.setBackground(new java.awt.Color(51, 51, 51));
        btnConvenioT.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConvenioT.setForeground(new java.awt.Color(255, 255, 255));
        btnConvenioT.setText("Convenio de Trabajo");
        btnConvenioT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnConvenioT.setContentAreaFilled(false);
        btnConvenioT.setFocusPainted(false);
        btnConvenioT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConvenioTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConvenioTMouseExited(evt);
            }
        });
        getContentPane().add(btnConvenioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, 40));

        jPanel4.setBackground(new java.awt.Color(173, 173, 173));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, 40));

        jPanel5.setBackground(new java.awt.Color(173, 173, 173));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 40));

        jPanel6.setBackground(new java.awt.Color(173, 173, 173));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 40));

        jPanel8.setBackground(new java.awt.Color(173, 173, 173));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, 40));

        jPanel1.setBackground(new java.awt.Color(173, 173, 173));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, 40));

        jHojita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHojita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/convenio.png"))); // NOI18N
        getContentPane().add(jHojita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 7, 170, 170));

        jTitulo.setBackground(new java.awt.Color(51, 51, 51));
        jTitulo.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("Acuerdos y Pagos");
        jTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 350, 50));

        jPanel7.setBackground(new java.awt.Color(173, 173, 173));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 350, 50));

        jPanel3.setBackground(new java.awt.Color(173, 173, 173));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jPanel3.add(jAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 32, 32));

        btnRegresar.setBackground(new java.awt.Color(51, 51, 51));
        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("   Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        jPanel3.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 171, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 172, 50));

        jImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contratoMini.png"))); // NOI18N
        getContentPane().add(jImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 250));

        jFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAcuerdos.jpg"))); // NOI18N
        getContentPane().add(jFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 670, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setContentAreaFilled(true);
        jAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnContratosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratosMouseEntered
        btnContratos.setContentAreaFilled(true);
    }//GEN-LAST:event_btnContratosMouseEntered

    private void btnContratosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratosMouseExited
        btnContratos.setContentAreaFilled(false);
    }//GEN-LAST:event_btnContratosMouseExited

    private void btnMetodosPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetodosPagoMouseEntered
        btnMetodosPago.setContentAreaFilled(true);
    }//GEN-LAST:event_btnMetodosPagoMouseEntered

    private void btnMetodosPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetodosPagoMouseExited
        btnMetodosPago.setContentAreaFilled(false);
    }//GEN-LAST:event_btnMetodosPagoMouseExited

    private void btnConvenioTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvenioTMouseEntered
        btnConvenioT.setContentAreaFilled(true);
    }//GEN-LAST:event_btnConvenioTMouseEntered

    private void btnConvenioTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvenioTMouseExited
        btnConvenioT.setContentAreaFilled(false);
    }//GEN-LAST:event_btnConvenioTMouseExited

    private void btnRenovacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRenovacionMouseEntered
        btnRenovacion.setContentAreaFilled(true);
    }//GEN-LAST:event_btnRenovacionMouseEntered

    private void btnRenovacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRenovacionMouseExited
        btnRenovacion.setContentAreaFilled(false);
    }//GEN-LAST:event_btnRenovacionMouseExited

    private void btnConvenioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvenioMouseEntered
        btnConvenio.setContentAreaFilled(true);
    }//GEN-LAST:event_btnConvenioMouseEntered

    private void btnConvenioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvenioMouseExited
        btnConvenio.setContentAreaFilled(false);
    }//GEN-LAST:event_btnConvenioMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnContratos;
    public javax.swing.JButton btnConvenio;
    public javax.swing.JButton btnConvenioT;
    public javax.swing.JButton btnMetodosPago;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnRenovacion;
    private javax.swing.JLabel jAtras;
    private javax.swing.JLabel jFondoMenu;
    private javax.swing.JLabel jHojita;
    private javax.swing.JLabel jImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
