/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.principal;

import javax.swing.ImageIcon;

/**
 *
 * @author jose-
 */
public class Adopcion extends javax.swing.JFrame {

    /**
     * Creates new form VariedadCerezas
     */
    public Adopcion() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoApp.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrograma = new javax.swing.JButton();
        btnPadrino = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jCereza = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jAtras = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jImagen = new javax.swing.JLabel();
        jFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrograma.setBackground(new java.awt.Color(255, 51, 51));
        btnPrograma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPrograma.setForeground(new java.awt.Color(255, 255, 255));
        btnPrograma.setText("Programa de Apa.");
        btnPrograma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPrograma.setContentAreaFilled(false);
        btnPrograma.setFocusPainted(false);
        btnPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProgramaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProgramaMouseExited(evt);
            }
        });
        getContentPane().add(btnPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, 45));

        btnPadrino.setBackground(new java.awt.Color(255, 51, 51));
        btnPadrino.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPadrino.setForeground(new java.awt.Color(255, 255, 255));
        btnPadrino.setText("Padrino");
        btnPadrino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPadrino.setContentAreaFilled(false);
        btnPadrino.setFocusPainted(false);
        btnPadrino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPadrinoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPadrinoMouseExited(evt);
            }
        });
        getContentPane().add(btnPadrino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, 45));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, 43));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, 43));

        jCereza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCereza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerezas.png"))); // NOI18N
        getContentPane().add(jCereza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 170));

        jTitulo.setBackground(new java.awt.Color(82, 171, 28));
        jTitulo.setFont(new java.awt.Font("Bookman Old Style", 1, 35)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("Adopcion de Cerezo");
        jTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 380, -1));

        jPanel7.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 380, 45));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jPanel3.add(jAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 32, 32));

        btnRegresar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("   Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        jPanel3.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 172, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 172, 50));

        jImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/programaMini.png"))); // NOI18N
        getContentPane().add(jImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 250, 250));

        jFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoCereza.jpg"))); // NOI18N
        getContentPane().add(jFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-24, 0, 620, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setContentAreaFilled(true);
        jAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png")));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnProgramaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProgramaMouseEntered
        btnPrograma.setContentAreaFilled(true);
    }//GEN-LAST:event_btnProgramaMouseEntered

    private void btnProgramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProgramaMouseExited
        btnPrograma.setContentAreaFilled(false);
    }//GEN-LAST:event_btnProgramaMouseExited

    private void btnPadrinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPadrinoMouseEntered
        btnPadrino.setContentAreaFilled(true);
    }//GEN-LAST:event_btnPadrinoMouseEntered

    private void btnPadrinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPadrinoMouseExited
        btnPadrino.setContentAreaFilled(false);
    }//GEN-LAST:event_btnPadrinoMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPadrino;
    public javax.swing.JButton btnPrograma;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jAtras;
    private javax.swing.JLabel jCereza;
    private javax.swing.JLabel jFondoMenu;
    private javax.swing.JLabel jImagen;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
