/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.principal;

import javax.swing.ImageIcon;

/**
 *
 * @author jose-
 */
public class Cargamentos extends javax.swing.JFrame {

    /**
     * Creates new form VariedadCerezas
     */
    public Cargamentos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoApp.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnvioReal = new javax.swing.JButton();
        btnVariedadExpor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jCajaCereza = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jAtras = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jImagen = new javax.swing.JLabel();
        jFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnvioReal.setBackground(new java.awt.Color(227, 141, 4));
        btnEnvioReal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEnvioReal.setForeground(new java.awt.Color(255, 255, 255));
        btnEnvioReal.setText("Envio Real");
        btnEnvioReal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnEnvioReal.setContentAreaFilled(false);
        btnEnvioReal.setFocusPainted(false);
        btnEnvioReal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnvioRealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnvioRealMouseExited(evt);
            }
        });
        getContentPane().add(btnEnvioReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 45));

        btnVariedadExpor.setBackground(new java.awt.Color(227, 141, 4));
        btnVariedadExpor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVariedadExpor.setForeground(new java.awt.Color(255, 255, 255));
        btnVariedadExpor.setText("Variedad Exportada");
        btnVariedadExpor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnVariedadExpor.setContentAreaFilled(false);
        btnVariedadExpor.setFocusPainted(false);
        btnVariedadExpor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVariedadExporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVariedadExporMouseExited(evt);
            }
        });
        getContentPane().add(btnVariedadExpor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 190, 45));

        jPanel4.setBackground(new java.awt.Color(255, 200, 80));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 43));

        jPanel5.setBackground(new java.awt.Color(255, 200, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 190, 43));

        jCajaCereza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCajaCereza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cajaCereza.png"))); // NOI18N
        getContentPane().add(jCajaCereza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 170));

        jTitulo.setBackground(new java.awt.Color(82, 171, 28));
        jTitulo.setFont(new java.awt.Font("Bookman Old Style", 1, 35)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("Cargamentos y Envios");
        jTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 420, -1));

        jPanel7.setBackground(new java.awt.Color(255, 200, 80));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 420, 45));

        jPanel3.setBackground(new java.awt.Color(255, 200, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jPanel3.add(jAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 32, 32));

        btnRegresar.setBackground(new java.awt.Color(227, 141, 4));
        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("   Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        jPanel3.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 172, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 172, 50));

        jImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargamentoMini.png"))); // NOI18N
        getContentPane().add(jImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 250, 250));

        jFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAlmacen.jpg"))); // NOI18N
        getContentPane().add(jFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setContentAreaFilled(true);
        jAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png")));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnEnvioRealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnvioRealMouseEntered
        btnEnvioReal.setContentAreaFilled(true);
    }//GEN-LAST:event_btnEnvioRealMouseEntered

    private void btnEnvioRealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnvioRealMouseExited
        btnEnvioReal.setContentAreaFilled(false);
    }//GEN-LAST:event_btnEnvioRealMouseExited

    private void btnVariedadExporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVariedadExporMouseEntered
        btnVariedadExpor.setContentAreaFilled(true);
    }//GEN-LAST:event_btnVariedadExporMouseEntered

    private void btnVariedadExporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVariedadExporMouseExited
        btnVariedadExpor.setContentAreaFilled(false);
    }//GEN-LAST:event_btnVariedadExporMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEnvioReal;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnVariedadExpor;
    private javax.swing.JLabel jAtras;
    private javax.swing.JLabel jCajaCereza;
    private javax.swing.JLabel jFondoMenu;
    private javax.swing.JLabel jImagen;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
