/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.principal;

import javax.swing.ImageIcon;

/**
 *
 * @author jose-
 */
public class Produccion extends javax.swing.JFrame {

    /**
     * Creates new form VariedadCerezas
     */
    public Produccion() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoApp.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVariedadCereza = new javax.swing.JButton();
        btnCultivo = new javax.swing.JButton();
        btnPrecios = new javax.swing.JButton();
        btnProduccionAnual = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jHojita = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jAtras = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jImagen = new javax.swing.JLabel();
        jFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVariedadCereza.setBackground(new java.awt.Color(13, 77, 24));
        btnVariedadCereza.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVariedadCereza.setForeground(new java.awt.Color(255, 255, 255));
        btnVariedadCereza.setText("Variedad de Cereza");
        btnVariedadCereza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnVariedadCereza.setContentAreaFilled(false);
        btnVariedadCereza.setFocusPainted(false);
        btnVariedadCereza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVariedadCerezaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVariedadCerezaMouseExited(evt);
            }
        });
        getContentPane().add(btnVariedadCereza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 45));

        btnCultivo.setBackground(new java.awt.Color(13, 77, 24));
        btnCultivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCultivo.setForeground(new java.awt.Color(255, 255, 255));
        btnCultivo.setText("Cultivo de Cereza");
        btnCultivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCultivo.setContentAreaFilled(false);
        btnCultivo.setFocusPainted(false);
        btnCultivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCultivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCultivoMouseExited(evt);
            }
        });
        getContentPane().add(btnCultivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 45));

        btnPrecios.setBackground(new java.awt.Color(13, 77, 24));
        btnPrecios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPrecios.setForeground(new java.awt.Color(255, 255, 255));
        btnPrecios.setText("Precios por Paises");
        btnPrecios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPrecios.setContentAreaFilled(false);
        btnPrecios.setFocusPainted(false);
        btnPrecios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPreciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPreciosMouseExited(evt);
            }
        });
        getContentPane().add(btnPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 45));

        btnProduccionAnual.setBackground(new java.awt.Color(13, 77, 24));
        btnProduccionAnual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnProduccionAnual.setForeground(new java.awt.Color(255, 255, 255));
        btnProduccionAnual.setText("Produccion Anual");
        btnProduccionAnual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnProduccionAnual.setContentAreaFilled(false);
        btnProduccionAnual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProduccionAnualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProduccionAnualMouseExited(evt);
            }
        });
        getContentPane().add(btnProduccionAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 200, 45));

        jPanel4.setBackground(new java.awt.Color(82, 171, 28));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 43));

        jPanel5.setBackground(new java.awt.Color(82, 171, 28));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 43));

        jPanel6.setBackground(new java.awt.Color(82, 171, 28));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 43));

        jPanel1.setBackground(new java.awt.Color(82, 171, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 200, 43));

        jHojita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHojita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hojita.png"))); // NOI18N
        getContentPane().add(jHojita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 170));

        jTitulo.setBackground(new java.awt.Color(82, 171, 28));
        jTitulo.setFont(new java.awt.Font("Bookman Old Style", 1, 35)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("Producción de Cerezas");
        jTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 430, -1));

        jPanel7.setBackground(new java.awt.Color(82, 171, 28));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 430, 45));

        jPanel3.setBackground(new java.awt.Color(82, 171, 28));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jPanel3.add(jAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 32, 32));

        btnRegresar.setBackground(new java.awt.Color(13, 77, 24));
        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("   Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        jPanel3.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 172, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 172, 50));

        jImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siembraMini.png"))); // NOI18N
        getContentPane().add(jImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 250, 250));

        jFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoProductor.jpg"))); // NOI18N
        getContentPane().add(jFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 650, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setContentAreaFilled(true);
        jAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png")));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnVariedadCerezaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVariedadCerezaMouseEntered
        btnVariedadCereza.setContentAreaFilled(true);
    }//GEN-LAST:event_btnVariedadCerezaMouseEntered

    private void btnVariedadCerezaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVariedadCerezaMouseExited
        btnVariedadCereza.setContentAreaFilled(false);
    }//GEN-LAST:event_btnVariedadCerezaMouseExited

    private void btnCultivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCultivoMouseEntered
        btnCultivo.setContentAreaFilled(true);
    }//GEN-LAST:event_btnCultivoMouseEntered

    private void btnCultivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCultivoMouseExited
        btnCultivo.setContentAreaFilled(false);
    }//GEN-LAST:event_btnCultivoMouseExited

    private void btnPreciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreciosMouseEntered
        btnPrecios.setContentAreaFilled(true);
    }//GEN-LAST:event_btnPreciosMouseEntered

    private void btnPreciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreciosMouseExited
        btnPrecios.setContentAreaFilled(false);
    }//GEN-LAST:event_btnPreciosMouseExited

    private void btnProduccionAnualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduccionAnualMouseEntered
        btnProduccionAnual.setContentAreaFilled(true);
    }//GEN-LAST:event_btnProduccionAnualMouseEntered

    private void btnProduccionAnualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduccionAnualMouseExited
        btnProduccionAnual.setContentAreaFilled(false);
    }//GEN-LAST:event_btnProduccionAnualMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCultivo;
    public javax.swing.JButton btnPrecios;
    public javax.swing.JButton btnProduccionAnual;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnVariedadCereza;
    private javax.swing.JLabel jAtras;
    private javax.swing.JLabel jFondoMenu;
    private javax.swing.JLabel jHojita;
    private javax.swing.JLabel jImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
